### PR TITLE
Format no symbol

### PR DESCRIPTION
**Pull request by domwong**
Add new method for returning formatted money string with no currency symbol, just the numbers

### CODE REVIEW

**Comment by braceta** [comment]
No quite sure but this this might break some tests in email-service since some of the template filters use money formatting.

**Comment by domwong** [comment]
@braceta this shouldn't change the behaviour of existing calls - hopefully the unit tests would have caught anything

**Comment by braceta** [comment]
@domwong it might change the output though (whitespace) but no worries it must be an easy fix :) :+1:

**Comment by domwong** [comment]
{code}
dominic@Dominics-MacBook-Air:~/development/goworkspace/src/github.com/hailocab/email-service (master)$ 🚖  go test ./...
?   	github.com/hailocab/email-service	[no test files]
?   	github.com/hailocab/email-service/event	[no test files]
ok  	github.com/hailocab/email-service/handler	0.052s
?   	github.com/hailocab/email-service/proto	[no test files]
?   	github.com/hailocab/email-service/proto/send	[no test files]
?   	github.com/hailocab/email-service/proto/sendpostmark	[no test files]
ok  	github.com/hailocab/email-service/templating	8.540s
ok  	github.com/hailocab/email-service/templating/filters	0.021s
?   	github.com/hailocab/email-service/templating/templates	[no test files]
{code}

**Comment by braceta** [comment]
@domwong an action is worth 1000 words! Great :+1:

**Pull request merged**
